#!/usr/bin/env python3
"""Turn a flat binary into a C3 const byte array (kernel/src/xk_uprog.c3)."""
import sys

def main():
    if len(sys.argv) != 3:
        print("usage: mkbin.py <in.bin> <out.c3>", file=sys.stderr)
        sys.exit(1)
    data = open(sys.argv[1], "rb").read()
    if not data:
        print("empty input", file=sys.stderr)
        sys.exit(1)
    body = "\n".join(
        "    user_prog[%d] = (char)0x%02X;" % (i, b) for i, b in enumerate(data)
    )
    with open(sys.argv[2], "w") as f:
        f.write("module xk;\n\n")
        f.write("// generated by tools/mkbin.py -- do not edit\n")
        f.write("const int USER_PROG_LEN = %d;\n" % len(data))
        f.write("char[%d] user_prog;   // in BSS; filled by uprog_init()\n" % len(data))
        f.write("fn void uprog_init()\n{\n%s\n}\n" % body)
    print("wrote %s (%d bytes)" % (sys.argv[2], len(data)))

if __name__ == "__main__":
    main()